#!/bin/bash

DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

$DIR/bin/stream-radio \
  "http://mod.cri.cn/rus/news/xw190103.m4a"\
  "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"\
  1521\
  28\
  2\
  &
