#!/bin/bash

DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

$DIR/bin/stream-radio \
  "http://online.carnivalfm.ru:8000/stream/2/"\
  "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"\
  1512\
  120\
  90\
  &
