#!/bin/bash

DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

$DIR/bin/stream-radio \
  "http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_128kbps"\
  "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"\
  810\
  150\
  60\
  802\
  &
