#!/bin/bash

DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

$DIR/bin/stream-radio \
  "http://radio02-cn03.akadostream.ru:8113/karnavalfm128.mp3"\
  "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"\
  1206\
  5\
  18\
  &
