#!/bin/bash

DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

$DIR/bin/stream-radio \
  "http://icecast-vgtrk.cdnvideo.ru/unost_mp3_128kbps"\
  "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"\
  153\
  12\
  8\
  &
